{% set name = "pynumpress" %}
{% set version = "0.0.6" %}
{% set sha256 = "a5d4633ad48cb5657b38c518abe320094bcf1465190732919622e1ab9a906f56" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - pynumpress

about:
  home: https://github.com/mobiusklein/pynumpress
  license: Apache-2.0
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A thin, more convenient wrapper around MSNumpress

extra:
  recipe-maintainers:
    - corburn
