{% set name = "pynumpress" %}
{% set version = "0.0.4" %}
{% set sha256 = "14d38dddf448c3afbe22c14185ed0f9f0d74306826732d1c81cdd754d75f10f4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - pynumpress

about:
  home: https://github.com/mobiusklein/pynumpress
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: A thin, more convenient wrapper around MSNumpress

extra:
  recipe-maintainers:
    - corburn
