travis:
  secure:
    BINSTAR_TOKEN: A6RkKwbYiObzHljPTZfoqliA+i1GuFOYc+QS4Oxw/PsnSyKwu19b8P2q1EqrhnM6F2MAlSqtnGAcnpDfYWcpHmzgQ/EyopT+HECapzSjR+a3KMCCnxHFb+S6LHV+IUGB1aWzTt5a7uC+eMlsON9FreVGKLU70fWim/J76K0vOTUJUHwitbHDJaApGSLJ5LlwfFcAsWSfjNBmA4F30SrjWyy7TbYSQOu8jblo4yFrj32cUiDzAVhj61/qODR070iPyBtu+DhSIaoRiyjrHE7TixmEHfQo6BCyENL0tobGDETM2expc+/r3zfsMh6+RfatAXriVh9q0IW+gPWrFOHERCODX+btkYRIkdiCtux5+FLZwLecXPsbH3/C2ohrAQDOeHvfR4z8meDyJ1eG9zAEBQ57vC5WkqmJRzFa6wwpHKjV2dGmU9+D/VhhONq85jaNqVMEeF7bGnXp0KINDIvZzbnZsHFTAwiE7gogdAVOI4iKViadiZb9TkehQl16FqhZmfi/1CS1SfCafm+L02ziQDy6Mvvn0Th9tyNIjhdZsHHHBm5goOmbfSPpCJVOFBF7oBghRCe2ilcB4n6YvGkhZPWsc9hZuAG8+7MRpfpGBj74zmFS1//XtVu3JpdeMu6P3gL0MH3lOkz032t2c2dMMzzJJpJZ9f6OpzSgukEVe1U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
